### ISSUE TITLE
request translation permission(Testing Bun's compatibility with Node.js and speed with a complex application)

### ISSUE THREAD

**Issue by jung-han** [robogeek/typescript-nodejs-quick-start#4]
Hi @robogeek! I'm jung, a front-end developer At Korean FE Article Team.

First of all, I am sorry that I chose this issue while looking for a place to contact.

I read an article([Testing Bun's compatibility with Node.js and speed with a complex application](https://techsparx.com/nodejs/bun/1st-trial.html)). It was a very good article and it was very helpful. I am going to translate the article into Korean and post it on Korean FE Article mailing substack(https://kofearticle.substack.com/), is it okay?

Korean FE Article is an activity that picks good FE articles every week, translates them into Korean, and shares them.
It is not used commercially, and the source must be identified.

Please think about it and reply. I'll wait!

**Comment by robogeek** [comment]
There is a serious problem with the article in that my test did not
properly compare Bun against Node.js.  I inserted a note in the article to
that effect.  I feel it would not be useful to further spread this article.

**Comment by jung-han** [comment]
Hi @robogeek. First of all, thank you for the quick reply.
Understand exactly which areas are concerned.

When I first read this article, what I felt was that you pointed out your concerns about a very simple test as you wrote down, and I also learned that you have to test at least to some extent.

I think it is still impossible to do the exact performance of Bun and Node.js itself. I think there are many things that can be learned from this article. In addition, I thought that it was clearly stated that the test may not be accurate and that the results may be different depending on the workflow.

And since this article has been widely mentioned in Korea, I thought it would be a good way to clearly mention the point of concern once again in the e-mail. It also feels worthwhile to re-emphasize and share your concerns clearly in the foreword of the email. What do you think?

If you are still concerned, I will destroy the translated text. I look forward to your reply!

**Comment by jung-han** [comment]
@robogeek 
I will close this issue. Thanks again for the good article,I will not share the translation. Please let me know if you change your mind later. Thank you!
